
services:
  app:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 4000:3000
    image: nateenglert2304/order_system:latest
    depends_on: mongodb
  mongodb:
    image: mongo-latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:


