
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  app:
    image: nateenglert2304/order_system:latest
    depends_on: 
      - mongodb
    environment:
      - PORT=3000
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=order_system
    ports:
      - "4000:3000"

volumes:
  mongo-data:


